### ISSUE TITLE
I'm seeing an error in the Error Console when opening the settings/preferences window for Scriptish

### ISSUE THREAD

**Issue by erikvold** [scriptish/scriptish#148]
[20:25:59.476] undefined: An exception occurred.
TypeError: prefNodes[i].name is undefined
chrome://scriptish/content/js/options.js 59
Traceback (most recent call last):
  File "resource://gre/modules/commonjs/sdk/timers.js", line 31, in notify
    callback.apply(null, args);
  File "chrome://scriptish/content/js/options.js", line 59, in checkSync
    prefNames.push(prefNodes[i].name.replace(RE_scriptishPrefix, ""));

**Comment by erikvold** [comment]
Don't see it now.
